sudo: required

services:
  - docker

before_install:
  - docker-compose build

script:
  - docker-compose up -d
  - curl localhost/healthcheck

before_deploy:
  - docker login --username $DOCKER_LOGIN_USERNAME --password $DOCKER_LOGIN_PASSWORD

deploy:
  provider: script
  script:
    - docker push cookie-cage/resume-subscription-api:latest
    - docker push cookie-cage/resume-subscription-api:v0.0.1
  on:
    branch: master
