version: "3"
services:
  mongo:
    image: mongo:3.4.4
    ports:
      - 27017:27017
  api:
    image: rezme/resume-subscription-api
    build:
      context: .
    volumes:
      - .:/opt/app
    env_file: .env
    ports:
      - 80:80
    depends_on:
      - mongo
